IF NOT EXISTS(SELECT * FROM SYS.tables WHERE NAME = 'TB_OBRA')
BEGIN
	CREATE TABLE dbo.TB_OBRA
	(
		  ObrId INT IDENTITY(1,1) NOT NULL
		, ObrApelido VARCHAR(40) NOT NULL
		, ObrDataInicio DATETIME NOT NULL
		, ObrDataFim DATETIME NULL
		, ObrEndereco VARCHAR(100) NULL
		, ObrOrcamento DECIMAL(38,2) NULL
		, ObrStatus BIT NOT NULL DEFAULT 0

		, CONSTRAINT PK_TB_OBRA_OBR_ID PRIMARY KEY(ObrId)
	)
END
GO