IF NOT EXISTS(SELECT * FROM SYS.tables WHERE NAME = 'TB_FUNCAO_FUNCIONARIO')
BEGIN
	CREATE TABLE dbo.TB_FUNCAO_FUNCIONARIO
	(
		  FnfId INT IDENTITY(1,1) NOT NULL
		, FnfNome VARCHAR(40) NOT NULL

		, CONSTRAINT PK_TB_FUNCAO_FUNCIONARIO_FNF_ID PRIMARY KEY(FnfId)
	)
END
GO


IF NOT EXISTS(SELECT * FROM SYS.tables WHERE NAME = 'TB_FUNCIONARIO')
BEGIN
	CREATE TABLE dbo.TB_FUNCIONARIO
	(
		  FunId INT IDENTITY(1,1) NOT NULL
		, FnfId INT NOT NULL --FK
		, FunNome VARCHAR(40) NOT NULL
		, FunDiaria DECIMAL(8,2) NULL
		, FunMensal DECIMAL(8,2) NULL
		, FunDataContratacao DATETIME NULL
		, FunStatus BIT NOT NULL DEFAULT 0
	
		, CONSTRAINT PK_TB_FUNCIONARIO_FUN_ID PRIMARY KEY(FunId)
		, CONSTRAINT FK_TB_FUNCIONARIO_TB_FUNCAO_FUNCIONARIO_FNF_ID FOREIGN KEY(FnfId) REFERENCES TB_FUNCAO_FUNCIONARIO
	)
END
GO