IF NOT EXISTS(SELECT * FROM SYS.tables WHERE NAME = 'TB_USUARIO')
BEGIN
	CREATE TABLE dbo.TB_USUARIO
	(
		  UsaId INT IDENTITY(1,1) NOT NULL
		, UsaNome VARCHAR(40) NOT NULL
		, UsaEmail VARCHAR(200) NOT NULL
		, UsaSenha VARBINARY(64) NOT NULL
		, UsaSalt VARBINARY(64) NOT NULL
	
		, CONSTRAINT PK_TB_USUARIO_USA_ID PRIMARY KEY(UsaId)
	)
END
GO