IF EXISTS(SELECT 1 FROM SYSCOLUMNS where id = object_id('TB_DIA_TRABALHADO') and name = 'FunId')
	--ALTER TABLE TB_DIA_TRABALHADO DROP CONSTRAINT FK_TB_DIA_TRABALHADO_TB_FUNCIONARIO_FUN_ID
	ALTER TABLE TB_DIA_TRABALHADO DROP COLUMN FunId
GO