IF NOT EXISTS(SELECT * FROM SYS.tables WHERE NAME = 'TB_DIA_TRABALHADO_FUNCIONARIO')
BEGIN
	CREATE TABLE dbo.TB_DIA_TRABALHADO_FUNCIONARIO
	(
		  DtfId INT IDENTITY(1,1) NOT NULL
		, DitId INT NOT NULL
		, FunId INT NOT NULL
	
		, CONSTRAINT PK_TB_DIA_TRABALHADO_FUNCIONARIO_DTF_ID PRIMARY KEY(DtfId)
		, CONSTRAINT FK_TB_DIA_TRABALHADO_FUNCIONARIO_TB_DIA_TRABALHADO_DIT_ID FOREIGN KEY(DitId) REFERENCES TB_DIA_TRABALHADO
		, CONSTRAINT FK_TB_DIA_TRABALHADO_FUNCIONARIO_TB_FUNCIONARIO_FUN_ID FOREIGN KEY(FunId) REFERENCES TB_FUNCIONARIO
	)
END
GO